name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout  repo code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js for install & test
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Log in to DockerHub using secrets  set in GitHub repo
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Debug step — prints the exact docker build command (make sure username is correct)
      - name: Debug docker tag
        run: echo "docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest ."

      # 7. Build Docker image with tag including your DockerHub username
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest .

      # 8. Push image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-demo-app:latest
