name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests
      - name: Run tests
        run: npm test

      # 5. Log in to DockerHub
     
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Trim DOCKER_USERNAME secret and set env var
        run: echo "DOCKER_USERNAME=$(echo '${{ secrets.DOCKER_USERNAME }}' | tr -d '\n\r ')" >> $GITHUB_ENV

      - name: Debug trimmed username
        run: |
          echo "DOCKER_USERNAME='${DOCKER_USERNAME}'"
          echo "Building image with tag: ${DOCKER_USERNAME}/nodejs-demo-app:latest"

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/nodejs-demo-app:latest .

      - name: Push Docker image
        run: docker push $DOCKER_USERNAME/nodejs-demo-app:latest
